#!/usr/bin/env bash
#
# bg-cycle.py wrapper for sudo & refreshing background.
#

bg_dir="$HOME/.assets/backgrounds"

sudo bg-cycle.py "$1" "$2"
sudo chown -R "$USER":"$USER" "$bg_dir"
"$bg_dir/set-desktop-background"
